name 'test_proj'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures test_proj'
long_description 'Installs/Configures test_proj'
version '0.9.0'
