name 'lamp'
maintainer 'Alexey Kaytaz'
maintainer_email 'alexey@kaytaz.ru'
license 'all_rights'
description 'Installs/Configures lamp'
long_description 'Installs/Configures lamp'
issues_url 'aaa'
source_url 'bbb'
version '3.0.5'

depends 'firewall', '~> 2.4.0'
depends 'chef-sugar', '>= 0.0.0'
depends 'firewall', '~> 2.4.0'
depends 'httpd', '~> 0.3.4'
depends 'mysql', '~> 7.1.1'
depends 'mysql2_chef_gem', '~> 1.1.0'
depends 'database', '~> 5.1.2'
