name 'test_proj'
maintainer 'Alexey Kaytaz'
maintainer_email 'alexey@kaytaz.ru'
license 'all_rights'
description 'Installs/Configures test_proj'
long_description 'Installs/Configures test_proj'
version '2.8.20'

depends 'chef-sugar'
depends 'firewall', '~> 2.4.0'
depends 'chef-sugar' '>= 0.0.0'
depends 'firewall': '~> 2.4.0'
depends 'httpd': '~> 0.3.4'
depends 'mysql': '~> 7.1.1'
depends 'mysql2_chef_gem': '~> 1.1.0'
depends 'database': '~> 5.1.2'
